# Generated by Django 5.0.4 on 2024-04-12 22:17

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiftuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avater'),
        ),
        migrations.CreateModel(
            name='UserItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garri', models.CharField(blank=True, choices=[('', ''), ('Quarter', 'Quarter'), ('Half', 'Half'), ('1-bag', '1-bag'), ('No', 'No')], max_length=20, null=True)),
                ('rice', models.CharField(blank=True, choices=[('', ''), ('Quarter', 'Quarter'), ('Half', 'Half'), ('1-bag', '1-bag'), ('No', 'No')], max_length=20, null=True)),
                ('honey_beans', models.CharField(blank=True, choices=[('', ''), ('Quarter', 'Quarter'), ('Half', 'Half'), ('1-bag', '1-bag'), ('No', 'No')], max_length=10, null=True)),
                ('oloyin_beans', models.CharField(blank=True, choices=[('', ''), ('Quarter', 'Quarter'), ('Half', 'Half'), ('1-bag', '1-bag'), ('No', 'No')], max_length=10, null=True)),
                ('onions', models.CharField(blank=True, choices=[('', ''), ('1 pent', '1 pent'), ('2 pent', '2 pent'), ('Quarter bag', 'Quarter bag'), ('Half bag', 'Half bag'), ('1-bag', '1-bag'), ('No', 'No')], max_length=20, null=True)),
                ('spaghetti', models.CharField(blank=True, choices=[('', ''), ('Half Carton', 'Half-Carton'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=20, null=True)),
                ('indomie', models.CharField(blank=True, choices=[('', ''), ('Half Carton', 'Half-Carton'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=20, null=True)),
                ('duration', models.CharField(blank=True, choices=[('', ''), ('1st Quarter', '1st Quarter'), ('2nd Quarter', '2nd Quarter'), ('3rd Quarter', '3rd Quarter'), ('4th Quarter', '4th Quarter')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
