# Generated by Django 5.0.4 on 2024-04-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0002_alter_swiftuser_avatar_useritems'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritems',
            name='yam_tubers',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='swiftuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='mobile number'),
        ),
    ]
