# Generated by Django 5.0.4 on 2024-04-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0003_useritems_yam_tubers_alter_swiftuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritems',
            name='spaghetti',
        ),
        migrations.AddField(
            model_name='useritems',
            name='aunty_b_spag',
            field=models.CharField(blank=True, choices=[('', ''), ('Half-Carton', 'Half-Carton'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='g_penny_spag',
            field=models.CharField(blank=True, choices=[('', ''), ('Half-Carton', 'Half-Carton'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='duration',
            field=models.CharField(blank=True, choices=[('', ''), ('1st Quarter', '1st Quarter'), ('2nd Quarter', '2nd Quarter'), ('3rd Quarter', '3rd Quarter'), ('4th Quarter', '4th Quarter')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='garri',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='honey_beans',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='indomie',
            field=models.CharField(blank=True, choices=[('', ''), ('Half Carton', 'Half-Carton'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='oloyin_beans',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='onions',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('3-quarter(0.75)', '3-quarter(0.75)'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='rice',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter', 'Quarter'), ('Half', 'Half'), ('1-bag', '1-bag'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='yam_tubers',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('No', 'No')], max_length=40, null=True),
        ),
    ]
