# Generated by Django 5.0.4 on 2024-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0004_remove_useritems_spaghetti_useritems_aunty_b_spag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritems',
            name='indomie',
        ),
        migrations.AddField(
            model_name='useritems',
            name='chikki_noodles',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='oriental_noodles',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
    ]
