# Generated by Django 5.0.4 on 2024-04-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0005_remove_useritems_indomie_useritems_chikki_noodles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritems',
            old_name='garri',
            new_name='drum_beans',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='oloyin_beans',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='rice',
        ),
        migrations.AddField(
            model_name='useritems',
            name='foreign_rice',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('2-bags', '2-bags'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='nig_rice',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('2-bags', '2-bags'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='white_garri',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('2-bag', '2-bag'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='yellow_garri',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('2-bag', '2-bag'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='aunty_b_spag',
            field=models.CharField(blank=True, choices=[('', ''), ('Half(0.5)', 'Half(0.5)'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='chikki_noodles',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('2-Carton', '2-Carton'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='g_penny_spag',
            field=models.CharField(blank=True, choices=[('', ''), ('Half(0.5)', 'Half(0.5)'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='onions',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('3-quarter(0.75)', '3-quarter(0.75)'), ('1', '1'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='oriental_noodles',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('2-Carton', '2-Carton'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
    ]
