# Generated by Django 5.0.4 on 2024-04-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0006_rename_garri_useritems_drum_beans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritems',
            name='red_oil',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1', '1'), ('2', '2'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='semo',
            field=models.CharField(blank=True, choices=[('', ''), ('1-bag', '1-bag'), ('2-bag', '2-bag'), ('2-bag', '2-bag'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='tomatoe',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1', '1'), ('2', '2'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='veg_oil',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1', '1'), ('2', '2'), ('No', 'No')], max_length=40, null=True),
        ),
    ]
