# Generated by Django 5.0.4 on 2024-04-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0007_useritems_red_oil_useritems_semo_useritems_tomatoe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritems',
            old_name='foreign_rice',
            new_name='foreign_rice_big_grain',
        ),
        migrations.RenameField(
            model_name='useritems',
            old_name='oriental_noodles',
            new_name='indomie_chicken',
        ),
        migrations.RenameField(
            model_name='useritems',
            old_name='onions',
            new_name='onions_big_size',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='tomatoe',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='white_garri',
        ),
        migrations.AddField(
            model_name='useritems',
            name='crown_spag',
            field=models.CharField(blank=True, choices=[('', ''), ('Half(0.5)', 'Half(0.5)'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='dangote_spag',
            field=models.CharField(blank=True, choices=[('', ''), ('Half(0.5)', 'Half(0.5)'), ('1-Carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='foreign_rice_small_grain',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('2-bags', '2-bags'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='indomie_oriental',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('2-Carton', '2-Carton'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='mimee_noodles',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('2-Carton', '2-Carton'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='onions_gen_size',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('3-quarter(0.75)', '3-quarter(0.75)'), ('1', '1'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='pelebe_beans',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='satchet_tomatoe',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-carton'), ('2-cartons', '2-cartons'), ('3-cartons', '3-cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='tin_tomatoe_220g',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1', '1'), ('2', '2'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='tin_tomatoe_450g',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1', '1'), ('2', '2'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='white_garri_bendel',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('2-bag', '2-bag'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='white_garri_ijebu',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('1-bag', '1-bag'), ('2-bag', '2-bag'), ('No', 'No')], max_length=40, null=True),
        ),
    ]
