# Generated by Django 5.0.4 on 2024-04-25 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0008_rename_foreign_rice_useritems_foreign_rice_big_grain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritems',
            name='chikki_noodles',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='indomie_chicken',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='indomie_oriental',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='mimee_noodles',
            field=models.CharField(blank=True, choices=[('', ''), ('1-carton', '1-Carton'), ('2-Cartons', '2-Cartons'), ('3-Cartons', '3-Cartons'), ('No', 'No')], max_length=40, null=True),
        ),
    ]
