# Generated by Django 5.0.4 on 2024-04-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0009_alter_useritems_chikki_noodles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritems',
            name='duration',
        ),
    ]
