# Generated by Django 5.0.4 on 2024-04-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0010_remove_useritems_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritems',
            name='duration',
            field=models.CharField(blank=True, choices=[('', ''), ('1st Quarter', '1st Quarter'), ('2nd Quarter', '2nd Quarter'), ('3rd Quarter', '3rd Quarter'), ('4th Quarter', '4th Quarter')], max_length=40, null=True),
        ),
    ]
