# Generated by Django 5.0.4 on 2024-04-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0013_swiftuser_togglestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('are_visible', models.BooleanField(default=False)),
            ],
        ),
    ]
