# Generated by Django 5.0.4 on 2024-04-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0015_rename_togglestatus_swiftuser_toggle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showelement',
            name='are_visible',
            field=models.BooleanField(default=True),
        ),
    ]
