# Generated by Django 5.0.4 on 2024-04-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0016_alter_showelement_are_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showelement',
            name='are_visible',
            field=models.BooleanField(default=False),
        ),
    ]
