# Generated by Django 5.0.4 on 2024-04-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0017_alter_showelement_are_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiftuser',
            name='toggle_status',
        ),
    ]
