# Generated by Django 5.0.4 on 2024-04-27 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0018_remove_swiftuser_toggle_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowElement',
        ),
    ]
