# Generated by Django 5.0.4 on 2024-04-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0019_delete_showelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritems',
            name='yam_tubers',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('No', 'No'), ('not-available', 'not-available')], default='', max_length=40, null=True),
        ),
    ]
