# Generated by Django 5.0.4 on 2024-05-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0022_remove_useritems_yam_tubers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritems',
            name='aunty_b_spag',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='chikki_noodles',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='crown_spag',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='dangote_spag',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='g_penny_spag',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='indomie_chicken',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='indomie_oriental',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='mimee_noodles',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='onions_big_size',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='onions_gen_size',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='satchet_tomatoe',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='semo',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='tin_tomatoe_220g',
        ),
        migrations.RemoveField(
            model_name='useritems',
            name='tin_tomatoe_450g',
        ),
    ]
