# Generated by Django 5.0.4 on 2024-05-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0023_remove_useritems_aunty_b_spag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useritems',
            old_name='yellow_garri',
            new_name='yellow_garri_bendel',
        ),
    ]
