# Generated by Django 5.0.4 on 2024-05-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiftapp', '0024_rename_yellow_garri_useritems_yellow_garri_bendel'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritems',
            name='onions_big_size',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('3-quarter(0.75)', '3-quarter(0.75)'), ('1', '1'), ('No', 'No')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='useritems',
            name='onions_gen_size',
            field=models.CharField(blank=True, choices=[('', ''), ('Quarter(0.25)', 'Quarter(0.25)'), ('Half(0.5)', 'Half(0.5)'), ('3-quarter(0.75)', '3-quarter(0.75)'), ('1', '1'), ('No', 'No')], max_length=40, null=True),
        ),
    ]
